services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - 8181:8080   # dışarıya 8181, container içinde 8080
      - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
    volumes:
      - ./weaviate_data:/var/lib/weaviate

# docker compose -f 'docker-compose.yml' up -d --build 

